id: I0429C400
legacy_id: P010688
ocr_import_info:
  bdrc_scan_id: W3888
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T07:40:37'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T12:13:45.513383+00:00'
last_modified: 2022-09-03 20:14:18.740841
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3888
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3888
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མདོ་ལས་བྱུང་བའི་གཏམ་རྒྱུད་སྣ་ཚོགས།
  author: ཞེ་ཆེན་རྒྱལ་ཚབ ༠༤་འགྱུར་མེད་པདྨ་རྣམ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.9229852022226586
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1PD27523:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD27523
      total_pages: 860
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD27523.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9229852022226586
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
